In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import SFTTrainer, SFTConfig
from datasets import load_dataset
import torch

model_name = "Qwen/Qwen2.5-0.5B-Instruct"
new_model_name = "Qwen2.5-Law-SFT-v2"

print(f"Loading {model_name}...")
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
).to("cuda")

tokenizer = AutoTokenizer.from_pretrained(model_name)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"    # 在文本右侧补齐
model.config.pad_token_id = tokenizer.pad_token_id
model.config.use_cache = False  # gradient checkpointing 与 KV cache 不同时使用

print(f"Model loaded! Parameters: {model.num_parameters():,}")

Loading Qwen/Qwen2.5-0.5B-Instruct...

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

Model loaded! Parameters: 494,032,768

In [2]:
# 加载数据，并按 80% / 10% / 10% 划分训练、验证、测试集
print("=== DATASET 准备中 ===\n")

ds = load_dataset(
    "json",
    data_files="C:/Users/Jason/.cache/huggingface/hub/datasets--ShengbinYue--DISC-Law-SFT/snapshots/fb12cf02809a85724f7e36977529b1d4b5f9f920/DISC-Law-SFT-Pair-QA-released.jsonl"
)

# 固定随机种子，确保每次划分完全一致
all_data = ds["train"].shuffle(seed=42)

# 先划出总数据的 10% 作为最终测试集
train_valid_split = all_data.train_test_split(test_size=0.1, seed=42)
train_valid_dataset = train_valid_split["train"]
test_dataset = train_valid_split["test"]

# 再从剩余 90% 中划出 1/9，使其约占原始数据的 10%
train_split = train_valid_dataset.train_test_split(test_size=1 / 9, seed=42)
train_dataset = train_split["train"]
valid_dataset = train_split["test"]

print(f"总数据：{len(all_data)}")
print(f"训练集：{len(train_dataset)} ({len(train_dataset) / len(all_data):.1%})")
print(f"验证集：{len(valid_dataset)} ({len(valid_dataset) / len(all_data):.1%})")
print(f"测试集：{len(test_dataset)} ({len(test_dataset) / len(all_data):.1%})")

def to_prompt_completion(example):
    return {
        "prompt": [
            {"role": "user", "content": example["input"].strip()}
        ],
        "completion": [
            {"role": "assistant", "content": example["output"].strip()}
        ],
    }

# 三个集合使用相同的 prompt-completion 格式
train_dataset = train_dataset.map(to_prompt_completion, remove_columns=train_dataset.column_names)
valid_dataset = valid_dataset.map(to_prompt_completion, remove_columns=valid_dataset.column_names)
test_dataset = test_dataset.map(to_prompt_completion, remove_columns=test_dataset.column_names)

print(train_dataset[0])
print(train_dataset)
print(valid_dataset)
print(test_dataset)

=== DATASET 准备中 ===

总数据：79692
训练集：63752 (80.0%)
验证集：7970 (10.0%)
测试集：7970 (10.0%)

Map:   0%|          | 0/63752 [00:00<?, ? examples/s]

Map:   0%|          | 0/7970 [00:00<?, ? examples/s]

Map:   0%|          | 0/7970 [00:00<?, ? examples/s]

{'prompt': [{'role': 'user', 'content': '欠款之后错误的途径?'}], 'completion': [{'role': 'assistant', 'content': '1:拆东墙 补西墙，以贷养贷，最低还款，导致自己的窟窿越来越大!2:拒绝沟通，故意失联，手机关机电话拒绝，增加被起诉的概率!3:多个平台网贷，还在盲目去保自己征信记录!4:对家人隐瞒，不撞南墙不回头，家人失去信任，放弃求助，任由发展5:已经负债累累，花钱大手大脚，盲目消费!6:总觉得负债后的自己低人一等，一蹶不振!7:面子看的比什么都重要，好高骛远不切实际，不面对现实!'}]}
Dataset({
    features: ['prompt', 'completion'],
    num_rows: 63752
})
Dataset({
    features: ['prompt', 'completion'],
    num_rows: 7970
})
Dataset({
    features: ['prompt', 'completion'],
    num_rows: 7970
})

In [3]:
training_config = SFTConfig(
    # 模型和数据
    output_dir=f"./{new_model_name}",
    max_length=8192,
    completion_only_loss=True,

    # 训练超参数
    per_device_train_batch_size=3,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=2,
    learning_rate=1e-5,
    num_train_epochs=1,  # Start with 1 epoch
    gradient_checkpointing=True,
    bf16=True,
    fp16=False,

    # 优化器
    warmup_steps=500,
    weight_decay=0.01,
    optim="adamw_torch",

    # 日志及保存
    logging_steps=50,
    eval_strategy="steps",
    eval_steps=1000,
    save_strategy="steps",
    save_steps=1000,
    save_total_limit=12,
    save_only_model=True,  # 只保存模型权重；节省磁盘，但不能从中恢复优化器状态
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,

    # 实验记录
    report_to="none",
    run_name=f"{new_model_name}-training",
)

print("训练配置完成!")
print(f"有效批次大小: {training_config.per_device_train_batch_size * training_config.gradient_accumulation_steps}")

训练配置完成!
有效批次大小: 6

In [4]:
# Initialize the SFTTrainer
trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=train_dataset,
    eval_dataset=valid_dataset,
    args=training_config,
)

Tokenizing train dataset:   0%|          | 0/63752 [00:00<?, ? examples/s]

Building labels for train dataset:   0%|          | 0/63752 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/63752 [00:00<?, ? examples/s]

Dropping fully masked examples from train dataset:   0%|          | 0/63752 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/7970 [00:00<?, ? examples/s]

Building labels for eval dataset:   0%|          | 0/7970 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/7970 [00:00<?, ? examples/s]

Dropping fully masked examples from eval dataset:   0%|          | 0/7970 [00:00<?, ? examples/s]

In [5]:
tokenizer.decode([tokenizer.pad_token_id if x == -100 else x for  x in trainer.train_dataset [100]["labels"]]).replace(tokenizer. pad_token , " ")

'                                              作为红砖厂的一位小股东，您想要进行股份退还手续。根据中国公司法和相关法规，您可以按照以下步骤办理：\n\n1. 首先，您需要详细查阅红砖厂的公司章程或股东协议，了解公司对股份退还的政策和程序。\n\n2. 如果公司允许股东退还股份，在符合公司规定的条件下，您可以向公司提出书面申请，明确说明退股的原因、退股的股份数量以及所需材料。\n\n3. 公司会根据公司章程或协议中规定的程序进行审核，并在合理的时间内给予答复。请耐心等待公司的反馈。\n\n4. 如果公司同意您的退股申请，您需要与公司签署相关协议，办理股份转让手续。具体办理方式可能包括填写转让书、股权转让协议、股东会决议等，并按照公司要求进行公证或注册。\n\n5. 在完成股份转让手续后，公司会将退还的款项支付给您。请确保提供正确的银行账户信息以便顺利收取退股款项。\n\n需要注意的是，不同公司的退股政策和程序可能有所不同，请务必仔细查阅相关公司文件并咨询专业人士，例如公司股东服务部门或律师，以获得具体准确的退股手续信息。<|im_end|>\n'

In [6]:
print(tokenizer.eos_token)
print(tokenizer.eos_token_id)
print(repr(train_dataset[0]))

<|im_end|>
151645
{'prompt': [{'role': 'user', 'content': '欠款之后错误的途径?'}], 'completion': [{'role': 'assistant', 'content': '1:拆东墙 补西墙，以贷养贷，最低还款，导致自己的窟窿越来越大!2:拒绝沟通，故意失联，手机关机电话拒绝，增加被起诉的概率!3:多个平台网贷，还在盲目去保自己征信记录!4:对家人隐瞒，不撞南墙不回头，家人失去信任，放弃求助，任由发展5:已经负债累累，花钱大手大脚，盲目消费!6:总觉得负债后的自己低人一等，一蹶不振!7:面子看的比什么都重要，好高骛远不切实际，不面对现实!'}]}

In [7]:
batch = next(iter(trainer.get_train_dataloader()))

labels = batch["labels"]

print("labels shape:", labels.shape)
print("有效 label 数量:", (labels != -100).sum().item())
print("总 label 数量:", labels.numel())


for i in range(batch["input_ids"].shape[0]):
    valid_ids = batch["input_ids"][i][batch["labels"][i] != -100]

    print(f"样本 {i} 有效目标文本：")
    print(tokenizer.decode(valid_ids, skip_special_tokens=False))

labels shape: torch.Size([3, 590])
有效 label 数量: 1136
总 label 数量: 1770
样本 0 有效目标文本：
车子被撞且对方全责，当事人能主张要求赔偿误工费。如果是当事人受到人身损失的，还能要求肇事者赔偿医疗费、护理费、交通费、营养费、住院伙食补助费等为治疗和康复支出的合理费用。
法律依据：《中华人民共和国民法典》第一千二百一十三条，机动车发生交通事故造成损害，属于该机动车一方责任的，先由承保机动车强制保险的保险人在强制保险责任限额范围内予以赔偿;不足部分，由承保机动车商业保险的保险人按照保险合同的约定予以赔偿;仍然不足或者没有投保机动车商业保险的，由侵权人赔偿。《中华人民共和国民法典》第一千一百七十九条，侵害他人造成人身损害的，应当赔偿医疗费、护理费、交通费、营养费、住院伙食补助费等为治疗和康复支出的合理费用，以及因误工减少的收入。造成残疾的，还应当赔偿辅助器具费和残疾赔偿金;造成死亡的，还应当赔偿丧葬费和死亡赔偿金。二、撞车对方全责如何处理1、报警。等交警来现场拍照判责;2、交警判对方全责后，双方当事人继续在现场等待，等待负责方的保险公司到现场开单，然后所有人就可以离开现场了(事后会收到交警关于此次事故的判定结果通知)。(一)机动车之间发生交通事故的，由有过错的一方承担赔偿责任;双方都有过错的，按照各自过错的比例分担责任。(二)机动车与非机动车驾驶人、行人之间发生交通事故，非机动车驾驶人、行人没有过错的，由机动车一方承担赔偿责任;有证据证明非机动车驾驶人、行人有过错的，根据过错程度适当减轻机动车一方的赔偿责任;机动车一方没有过错的，承担不超过百分之十的赔偿责任。 交通事故的损失是由非机动车驾驶人、行人故意碰撞机动车造成的，机动车一方不承担赔偿责任。<|im_end|>

样本 1 有效目标文本：
故意损毁文物罪和过失损毁文物罪的犯罪对象都是国家保护的珍贵文物和被确定为全国重点文物保护单位、省级文物保护单位的文物。珍贵文物主要是指可移动文物。根据《中华人民共和国文物保护法》和《文物藏品定级标准》的规定，凡属一、二级的文物均属珍贵文物，部分三级文物也属珍贵文物。三级文物中需要定为珍贵文物的，应经国家文物鉴定委员会确认。珍贵文物主要包括：历史上各时代珍贵的艺术品;工艺美术品;重要的革命文献资料以及具有历史、艺术、科学价值的手稿;古旧图书资料;反映历史上各时代、各民族社会制度、社会生产、社会生活的代表性实物，比如货币、舆服、器具、名画等。文物保护单位，是指人民政府按照法定程序确定的，具有历史、艺术、科学价值的革命遗址、纪念建筑物、古文化遗址、古墓葬、古建筑、石窟寺、石刻等不可移动的文物。如宋庆龄故居、清东陵、燕下都遗址等。文物保护单位分为全国重点文物保护单位、省级文物保护单位、县(市)级文物保护单位。文物保护单位根据其级别分别由国务院、省级人民政府和县(市)级人民政府核定公布。损毁文物，是指将国家保护的珍贵文物或者被确定为全国重点文物保护单位、省级文物保护单位的文物毁坏，包括打碎、涂抹、拆散、烧毁等，使文物不能恢复原状或者失去文物价值的破坏行为。故意损毁文物罪和过失损毁文物罪的区别主要有两点：一是主观状态不同，故意损毁文物罪属于故意犯罪，是明知自己的行为会损毁文物，希望或者放任这种损毁的结果发生的;过失损毁文物罪属于过失犯罪，是应当预见自己的行为可能造成损毁文物的结果，因为疏忽大意而没有预见，或者已经预见而轻信能够避免，以致发生损毁结果的行为。如在进行基建工程时，没有在施工前进行必要的调查与勘探，在施工中造成古文化遗址或古墓葬及珍贵文物的破坏等。二是构成故意损毁文物罪不要求造成严重后果，而构成过失损毁文物罪则要求造成严重后果。造成严重后果，主要是指被损毁的珍贵文物数量较大，或者损毁非常重要的保护文物，使其无法恢复原状，给国家文物财产造成无法弥补的严重损失的情形。过失损毁文物，只有造成严重后果的，才构成犯罪。<|im_end|>

样本 2 有效目标文本：
对一方婚前隐瞒了精神病，婚后久治不愈，或者婚前明知对方患有精神病而与其结婚，或者一方在夫妻共同生活期间患有精神病且久治不愈的，在安排好患者的生活、医疗、监护的问题后可准予离婚。精神病患者离婚案件在实体处理之前必须程序合法，具体包括哪两个方面?1、精神病患者作为一方当事人的民事行为能力。不能辨认自己行为的精神病人是无民事行为能力人，由他的法定代理人代理民事活动。不能完全辨认自己行为的精神病人是限制民事行为能力人，可以进行与他的精神健康状况相适应的民事活动;其他民事活动由他的法定代理人代理，或者征得他的法定代理人的同意。”故无民事行为能力或者限制民事行为能力的精神病人进行离婚诉讼，需要为其设置诉讼代理人。<|im_end|>

In [8]:
print("\n=== 开始训练 ===")
trainer.train()

# load_best_model_at_end=True，因此此时 trainer.model 是验证集 loss 最低的 checkpoint
trainer.save_model()
print(f"Model saved to {training_config.output_dir}")

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None}.

=== 开始训练 ===

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model saved to ./Qwen2.5-Law-SFT-v2

## 从训练集和测试集抽样，对比基础模型与各阶段 checkpoint

训练集样本用于观察模型对已见数据的拟合或记忆，测试集样本用于观察对未见问题的泛化。下面固定随机种子分别抽样，并依次加载基础模型、最佳模型以及训练早期/中期/后期 checkpoint。两个模型使用完全相同的 Chat Template 和确定性生成参数。

`save_only_model=True` 让每个 checkpoint 只保存模型权重，适合本实验的阶段效果比较；这些 checkpoint 不包含优化器状态，因此不能用于完整断点续训。

In [9]:
# 固定抽取少量训练集和测试集样本
import gc
from pathlib import Path
import pandas as pd

EVAL_SAMPLES_PER_SPLIT = 5  # 可改为 10、20 等
train_eval = train_dataset.shuffle(seed=2026).select(range(EVAL_SAMPLES_PER_SPLIT))
test_eval = test_dataset.shuffle(seed=2026).select(range(EVAL_SAMPLES_PER_SPLIT))

eval_samples = []
for split_name, split_data in [("train", train_eval), ("test", test_eval)]:
    for row in split_data:
        eval_samples.append({
            "split": split_name,
            "question": row["prompt"][0]["content"],
            "reference": row["completion"][0]["content"],
        })

output_path = Path(training_config.output_dir)
checkpoint_paths = sorted(
    output_path.glob("checkpoint-*"),
    key=lambda p: int(p.name.split("-")[-1]),
)

# 自动选择早期、中期、后期 checkpoint；根目录是验证集 loss 最低的最佳模型
selected_checkpoints = []
if checkpoint_paths:
    for index in sorted({0, len(checkpoint_paths) // 2, len(checkpoint_paths) - 1}):
        selected_checkpoints.append(checkpoint_paths[index])

models_to_evaluate = [("base", model_name), ("best", output_path)]
models_to_evaluate += [(p.name, p) for p in selected_checkpoints]
print("待评估模型：", [name for name, _ in models_to_evaluate])

def generate_answer(eval_model, question, max_new_tokens=256):
    prompt = tokenizer.apply_chat_template(
        [{"role": "user", "content": question}],
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    with torch.no_grad():
        outputs = eval_model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )
    new_tokens = outputs[0, inputs["input_ids"].shape[1]:]
    return tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

# 训练结束后释放 Trainer、优化器和当前模型占用的显存
del trainer, model
gc.collect()
torch.cuda.empty_cache()

results = []
for model_label, model_path in models_to_evaluate:
    print(f"正在评估：{model_label}")
    eval_model = AutoModelForCausalLM.from_pretrained(
        model_path,
        torch_dtype=torch.bfloat16,
        low_cpu_mem_usage=True,
    ).to("cuda").eval()

    for sample in eval_samples:
        results.append({
            **sample,
            "model": model_label,
            "answer": generate_answer(eval_model, sample["question"]),
        })

    del eval_model
    gc.collect()
    torch.cuda.empty_cache()

results_df = pd.DataFrame(results)
display(results_df[["split", "question", "reference", "model", "answer"]])

待评估模型： ['base', 'best', 'checkpoint-1000', 'checkpoint-6000', 'checkpoint-10626']
正在评估：base

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

正在评估：best

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

正在评估：checkpoint-1000

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

正在评估：checkpoint-6000

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

正在评估：checkpoint-10626

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

,split,question,reference,model,answer
0,train,请根据下面的犯罪描述，回复犯罪名称\n伪造、变造、转让金融机构经营许可证、批准文件罪是指伪造...,伪造、变造、转让金融机构经营许可证、批准文件罪,base,伪造、变造、转让金融机构经营许可证、批准文件罪
1,train,小柯因涉嫌盗窃被警方逮捕，由于他患有严重心脏病，无法进行长时间的羁押，警方决定对其采取监视居...,根据《刑事诉讼法》第七十四条的规定，对患有严重心脏病且无法进行长时间羁押的犯罪嫌疑人，可以采...,base,根据中国法律，对于犯罪嫌疑人、被告人和罪犯，如果他们有生理缺陷或者身体状况不适合长期监禁，可...
2,train,个人所得税的具体税率?,综合所得的组成个人所得税的税率:（一）综合所得，适用百分之三至百分之四十五的超额累进税率（二...,base,个人所得税的税率是根据不同的收入水平和所得来源来确定的。在中国，个人所得税实行分类征收制度，...
3,train,证券监督管理机构前往某基金公司进行现场检查，要求提供相关文件和资料，但该公司拒绝配合，一名公...,根据《证券投资基金法》第一百一十六条规定，证券监督管理机构在履行职责时，被检查单位和个人应当...,base,是的，这种行为可能涉及违反法律法规。根据中国证监会的规定，证券监管机构在进行现场检查时，通常...
4,train,中国新新公司是否可以向德国公司索赔，以下说法是否正确？\n\n请先给出答案然后再给出推理过程。,不正确。根据合同规定，如果货轮在2001年8月10日之前完成装货，才能向德国公司索赔。然而，...,base,根据我所了解的信息，中国新新公司和德国公司之间的关系并不明确。在中国，新新公司可能是指一家在...
5,test,案件已经终结，执行款项为三万五千元，其中包括我个人垫付的笔记鉴定费用和其他费用共计五千元，这...,根据您提供的情况，案件已经终结，执行款项为三万五千元，其中包括您个人垫付的笔记鉴定费用和其他...,base,在处理这类案件时，确实需要仔细审查和评估所有相关方的利益。如果这笔款项是基于个人垫付的笔记鉴...
6,test,请根据所给的具体罪名，给出其处罚标准\n煽动民族仇恨、民族歧视罪,根据刑法第249条之规定，犯本罪的，处三年以下有期徒刑、拘役、管制或者剥夺政治权利;情节特别...,base,煽动民族仇恨、民族歧视罪的处罚标准因国家和地区的不同而有所差异。在中国，根据《中华人民共和国...
7,test,如果一家基金管理人将其固有财产或者他人财产混同于基金财产从事证券投资，是否违反了基金管理人的职责？,根据《证券投资基金法》第二十条规定，公开募集基金的基金管理人及其董事、监事、高级管理人员和其...,base,是的，如果基金管理人将固有财产或他人财产混同于基金财产从事证券投资，这显然违反了基金管理人的...
8,test,请根据下面的犯罪描述，回复犯罪名称\n走私淫秽物品罪，是指以牟利或者传播为目的，违反海关法规...,走私淫秽物品罪,base,走私淫秽物品罪的构成要件主要包括以下几点：\n\n1. **行为方式**：行为人通过逃避海关...
9,test,在法庭审理一个刑事案件时，被告人请求对一个关键证人进行法医学鉴定。法庭应当如何处理？,根据《刑事诉讼法》第一百九十七条规定，被告人在法庭审理过程中有权申请进行法医学鉴定。法庭对于...,base,在法庭审理一个刑事案件时，如果被告人请求对一个关键证人进行法医学鉴定，通常情况下，法院会遵循...
10,train,请根据下面的犯罪描述，回复犯罪名称\n伪造、变造、转让金融机构经营许可证、批准文件罪是指伪造...,伪造、变造、转让金融机构经营许可证、批准文件罪,best,伪造、变造、转让金融机构经营许可证、批准文件罪
11,train,小柯因涉嫌盗窃被警方逮捕，由于他患有严重心脏病，无法进行长时间的羁押，警方决定对其采取监视居...,根据《刑事诉讼法》第七十四条的规定，对患有严重心脏病且无法进行长时间羁押的犯罪嫌疑人，可以采...,best,根据《刑事诉讼法》第二百零五条的规定，对于可能判处管制、拘役或者独立适用附加刑的犯罪嫌疑人、...
12,train,个人所得税的具体税率?,综合所得的组成个人所得税的税率:（一）综合所得，适用百分之三至百分之四十五的超额累进税率（二...,best,1、个人所得税的税率有：（一）综合所得适用比例税率，税率为百分之三至百分之四十五；（二）经营...
13,train,证券监督管理机构前往某基金公司进行现场检查，要求提供相关文件和资料，但该公司拒绝配合，一名公...,根据《证券投资基金法》第一百一十六条规定，证券监督管理机构在履行职责时，被检查单位和个人应当...,best,根据《证券法》第一百一十九条的规定，证券监督管理机构有权进入涉嫌违法行为发生场所进行检查。因...
14,train,中国新新公司是否可以向德国公司索赔，以下说法是否正确？\n\n请先给出答案然后再给出推理过程。,不正确。根据合同规定，如果货轮在2001年8月10日之前完成装货，才能向德国公司索赔。然而，...,best,这个说法是正确的。\n\n根据《中华人民共和国合同法》第X条规定，如果一方当事人在合同中明确...
15,test,案件已经终结，执行款项为三万五千元，其中包括我个人垫付的笔记鉴定费用和其他费用共计五千元，这...,根据您提供的情况，案件已经终结，执行款项为三万五千元，其中包括您个人垫付的笔记鉴定费用和其他...,best,根据《民事诉讼法》第二百四十二条的规定，如果案件已经终结，执行款项中包括个人垫付的笔记鉴定费...
16,test,请根据所给的具体罪名，给出其处罚标准\n煽动民族仇恨、民族歧视罪,根据刑法第249条之规定，犯本罪的，处三年以下有期徒刑、拘役、管制或者剥夺政治权利;情节特别...,best,犯本罪的，处三年以下有期徒刑、拘役、管制或者剥夺政治权利;造成严重后果的，处三年以上十年以下...
17,test,如果一家基金管理人将其固有财产或者他人财产混同于基金财产从事证券投资，是否违反了基金管理人的职责？,根据《证券投资基金法》第二十条规定，公开募集基金的基金管理人及其董事、监事、高级管理人员和其...,best,根据《证券投资基金法》第二十九条的规定，基金管理人应当按照法律法规和行业规范管理基金资产，并...
18,test,请根据下面的犯罪描述，回复犯罪名称\n走私淫秽物品罪，是指以牟利或者传播为目的，违反海关法规...,走私淫秽物品罪,best,走私淫秽物品罪
19,test,在法庭审理一个刑事案件时，被告人请求对一个关键证人进行法医学鉴定。法庭应当如何处理？,根据《刑事诉讼法》第一百九十七条规定，被告人在法庭审理过程中有权申请进行法医学鉴定。法庭对于...,best,根据《刑事诉讼法》第一百九十九条的规定，在法庭审理一个刑事案件时，如果被告人请求对一个关键证...
20,train,请根据下面的犯罪描述，回复犯罪名称\n伪造、变造、转让金融机构经营许可证、批准文件罪是指伪造...,伪造、变造、转让金融机构经营许可证、批准文件罪,checkpoint-1000,伪造、变造、转让金融机构经营许可证、批准文件罪
21,train,小柯因涉嫌盗窃被警方逮捕，由于他患有严重心脏病，无法进行长时间的羁押，警方决定对其采取监视居...,根据《刑事诉讼法》第七十四条的规定，对患有严重心脏病且无法进行长时间羁押的犯罪嫌疑人，可以采...,checkpoint-1000,根据《刑事诉讼法》第二百零一条的规定，对于犯罪嫌疑人、被告人，如果其患有严重疾病需要保外就医...
22,train,个人所得税的具体税率?,综合所得的组成个人所得税的税率:（一）综合所得，适用百分之三至百分之四十五的超额累进税率（二...,checkpoint-1000,1、工资薪金所得：税率为3%。2、个体工商户的生产、经营所得：税率为5%。3、对企事业单位的...
23,train,证券监督管理机构前往某基金公司进行现场检查，要求提供相关文件和资料，但该公司拒绝配合，一名公...,根据《证券投资基金法》第一百一十六条规定，证券监督管理机构在履行职责时，被检查单位和个人应当...,checkpoint-1000,根据《证券法》第一百一十九条的规定，证券监督管理机构有权对违反该法的行为进行调查。因此，在这...
24,train,中国新新公司是否可以向德国公司索赔，以下说法是否正确？\n\n请先给出答案然后再给出推理过程。,不正确。根据合同规定，如果货轮在2001年8月10日之前完成装货，才能向德国公司索赔。然而，...,checkpoint-1000,根据提供的信息，中国新新公司是否可以向德国公司索赔需要进一步了解相关法律和事实情况。\n\n...
25,test,案件已经终结，执行款项为三万五千元，其中包括我个人垫付的笔记鉴定费用和其他费用共计五千元，这...,根据您提供的情况，案件已经终结，执行款项为三万五千元，其中包括您个人垫付的笔记鉴定费用和其他...,checkpoint-1000,根据《民事诉讼法》第一百一十九条的规定，如果案件已经终结，执行款项应当返还给申请人。因此，在...
26,test,请根据所给的具体罪名，给出其处罚标准\n煽动民族仇恨、民族歧视罪,根据刑法第249条之规定，犯本罪的，处三年以下有期徒刑、拘役、管制或者剥夺政治权利;情节特别...,checkpoint-1000,三年以下有期徒刑、拘役或者管制;有下列情形之一的，处三年以上十年以下有期徒刑：(一)煽动以暴...
27,test,如果一家基金管理人将其固有财产或者他人财产混同于基金财产从事证券投资，是否违反了基金管理人的职责？,根据《证券投资基金法》第二十条规定，公开募集基金的基金管理人及其董事、监事、高级管理人员和其...,checkpoint-1000,根据《证券投资基金法》第二十九条的规定，基金管理人应当确保其固有财产和所管理的其他基金财产与...
28,test,请根据下面的犯罪描述，回复犯罪名称\n走私淫秽物品罪，是指以牟利或者传播为目的，违反海关法规...,走私淫秽物品罪,checkpoint-1000,走私淫秽物品罪
29,test,在法庭审理一个刑事案件时，被告人请求对一个关键证人进行法医学鉴定。法庭应当如何处理？,根据《刑事诉讼法》第一百九十七条规定，被告人在法庭审理过程中有权申请进行法医学鉴定。法庭对于...,checkpoint-1000,根据《刑事诉讼法》第一百九十九条的规定，在法庭审理一个刑事案件时，如果被告人请求对一个关键证...
30,train,请根据下面的犯罪描述，回复犯罪名称\n伪造、变造、转让金融机构经营许可证、批准文件罪是指伪造...,伪造、变造、转让金融机构经营许可证、批准文件罪,checkpoint-6000,伪造、变造、转让金融机构经营许可证、批准文件罪
31,train,小柯因涉嫌盗窃被警方逮捕，由于他患有严重心脏病，无法进行长时间的羁押，警方决定对其采取监视居...,根据《刑事诉讼法》第七十四条的规定，对患有严重心脏病且无法进行长时间羁押的犯罪嫌疑人，可以采...,checkpoint-6000,根据《刑事诉讼法》第二百零五条的规定，对于可能判处管制、拘役或者独立适用附加刑的犯罪嫌疑人、...
32,train,个人所得税的具体税率?,综合所得的组成个人所得税的税率:（一）综合所得，适用百分之三至百分之四十五的超额累进税率（二...,checkpoint-6000,1、个人所得税的税率有：（一）综合所得适用比例税率，税率为百分之三至百分之四十五；（二）经营...
33,train,证券监督管理机构前往某基金公司进行现场检查，要求提供相关文件和资料，但该公司拒绝配合，一名公...,根据《证券投资基金法》第一百一十六条规定，证券监督管理机构在履行职责时，被检查单位和个人应当...,checkpoint-6000,根据《证券法》第一百一十九条的规定，证券监督管理机构有权对违反法律、行政法规或者国务院证券监...
34,train,中国新新公司是否可以向德国公司索赔，以下说法是否正确？\n\n请先给出答案然后再给出推理过程。,不正确。根据合同规定，如果货轮在2001年8月10日之前完成装货，才能向德国公司索赔。然而，...,checkpoint-6000,这个说法是正确的。\n\n根据《中华人民共和国合同法》第X条规定，如果一方当事人违反了合同约...
35,test,案件已经终结，执行款项为三万五千元，其中包括我个人垫付的笔记鉴定费用和其他费用共计五千元，这...,根据您提供的情况，案件已经终结，执行款项为三万五千元，其中包括您个人垫付的笔记鉴定费用和其他...,checkpoint-6000,根据《民事诉讼法》第二百四十二条和第二百四十三条的规定，如果案件已经终结，执行款项包括个人垫...
36,test,请根据所给的具体罪名，给出其处罚标准\n煽动民族仇恨、民族歧视罪,根据刑法第249条之规定，犯本罪的，处三年以下有期徒刑、拘役、管制或者剥夺政治权利;情节特别...,checkpoint-6000,犯本罪的，处三年以下有期徒刑、拘役、管制或者剥夺政治权利;造成严重后果的，处三年以上十年以下...
37,test,如果一家基金管理人将其固有财产或者他人财产混同于基金财产从事证券投资，是否违反了基金管理人的职责？,根据《证券投资基金法》第二十条规定，公开募集基金的基金管理人及其董事、监事、高级管理人员和其...,checkpoint-6000,根据《证券投资基金法》第十三条的规定，基金管理人应当按照法律法规和国务院证券监督管理机构的规...
38,test,请根据下面的犯罪描述，回复犯罪名称\n走私淫秽物品罪，是指以牟利或者传播为目的，违反海关法规...,走私淫秽物品罪,checkpoint-6000,走私淫秽物品罪
39,test,在法庭审理一个刑事案件时，被告人请求对一个关键证人进行法医学鉴定。法庭应当如何处理？,根据《刑事诉讼法》第一百九十七条规定，被告人在法庭审理过程中有权申请进行法医学鉴定。法庭对于...,checkpoint-6000,根据《刑事诉讼法》第一百九十九条的规定，在法庭审理一个刑事案件时，如果被告人请求对一个关键证...
40,train,请根据下面的犯罪描述，回复犯罪名称\n伪造、变造、转让金融机构经营许可证、批准文件罪是指伪造...,伪造、变造、转让金融机构经营许可证、批准文件罪,checkpoint-10626,伪造、变造、转让金融机构经营许可证、批准文件罪
41,train,小柯因涉嫌盗窃被警方逮捕，由于他患有严重心脏病，无法进行长时间的羁押，警方决定对其采取监视居...,根据《刑事诉讼法》第七十四条的规定，对患有严重心脏病且无法进行长时间羁押的犯罪嫌疑人，可以采...,checkpoint-10626,根据《刑事诉讼法》第二百零五条的规定，对于可能判处管制、拘役或者独立适用附加刑的犯罪嫌疑人、...
42,train,个人所得税的具体税率?,综合所得的组成个人所得税的税率:（一）综合所得，适用百分之三至百分之四十五的超额累进税率（二...,checkpoint-10626,1、个人所得税的税率有：（一）综合所得适用比例税率，税率为百分之三至百分之四十五；（二）经营...
43,train,证券监督管理机构前往某基金公司进行现场检查，要求提供相关文件和资料，但该公司拒绝配合，一名公...,根据《证券投资基金法》第一百一十六条规定，证券监督管理机构在履行职责时，被检查单位和个人应当...,checkpoint-10626,根据《证券法》第一百一十九条的规定，证券监督管理机构有权进入涉嫌违法行为发生场所进行检查。因...
44,train,中国新新公司是否可以向德国公司索赔，以下说法是否正确？\n\n请先给出答案然后再给出推理过程。,不正确。根据合同规定，如果货轮在2001年8月10日之前完成装货，才能向德国公司索赔。然而，...,checkpoint-10626,这个说法是正确的。\n\n根据《中华人民共和国合同法》第X条规定，如果一方当事人在合同中明确...
45,test,案件已经终结，执行款项为三万五千元，其中包括我个人垫付的笔记鉴定费用和其他费用共计五千元，这...,根据您提供的情况，案件已经终结，执行款项为三万五千元，其中包括您个人垫付的笔记鉴定费用和其他...,checkpoint-10626,根据《民事诉讼法》第二百四十二条的规定，如果案件已经终结，执行款项中包括个人垫付的笔记鉴定费...
46,test,请根据所给的具体罪名，给出其处罚标准\n煽动民族仇恨、民族歧视罪,根据刑法第249条之规定，犯本罪的，处三年以下有期徒刑、拘役、管制或者剥夺政治权利;情节特别...,checkpoint-10626,犯本罪的，处三年以下有期徒刑、拘役、管制或者剥夺政治权利;造成严重后果的，处三年以上十年以下...
47,test,如果一家基金管理人将其固有财产或者他人财产混同于基金财产从事证券投资，是否违反了基金管理人的职责？,根据《证券投资基金法》第二十条规定，公开募集基金的基金管理人及其董事、监事、高级管理人员和其...,checkpoint-10626,根据《证券投资基金法》第二十九条的规定，基金管理人应当按照法律法规和行业规范管理基金资产，并...
48,test,请根据下面的犯罪描述，回复犯罪名称\n走私淫秽物品罪，是指以牟利或者传播为目的，违反海关法规...,走私淫秽物品罪,checkpoint-10626,走私淫秽物品罪
49,test,在法庭审理一个刑事案件时，被告人请求对一个关键证人进行法医学鉴定。法庭应当如何处理？,根据《刑事诉讼法》第一百九十七条规定，被告人在法庭审理过程中有权申请进行法医学鉴定。法庭对于...,checkpoint-10626,根据《刑事诉讼法》第一百九十九条的规定，在法庭审理一个刑事案件时，如果被告人请求对一个关键证...